### ISSUE TITLE
Version 1.6.0 doesn't work

### ISSUE THREAD

**Issue by jardicc** [runegan/jsxbin#11]
Version 1.6.0 doesn't work for me. It does not generate files. And I don't see any ESTK window. I didn't try to figure out what is going on I just downgraded to 1.5.1 which works good for me.

**Comment by runegan** [comment]
This very possibly related to this: https://github.com/runegan/jsxbin/commit/901052619157cb7e97838142b13a2d7187466829#commitcomment-31639346

I'm unsure how to address this at the moment

**Comment by runegan** [comment]
This should be resolved now that we are no longer using the ESTK application
