### ISSUE TITLE
output file is empty

### ISSUE THREAD

**Issue by santaclauze** [runegan/jsxbin#14]
Hey, first of all thanks for the lib. Saved me a lot of hassle.

However, I have an issue regarding the following line:

```js
jsxbin( 'path/to/script.js', 'output/script.jsxbin' )
	.then( outputfiles => {
		console.log( 'Finished!' )
	})
	.catch( err => {
		console.error( err )
	})

```

While the script succeeds, and creates the `output` folder, it remains empty. The only way I have had the script working is by using it as follows:

```js
jsxbin( 'path/to/script.js')
```

Am I missing something?

**Comment by santaclauze** [comment]
Hey again,

I am coming back here because while I have actually succeeded to use the library it only works when my file to convert is a sibling of the file that calls your function.

ex: `computer/dir/myScriptThatCallsJsxToJsxbin`, `computer/dir/my.jsx` <- this works but if I do:
`computer/otherDir/my.jsx` it cannot find it.

**Comment by runegan** [comment]
I cannot reproduce this on my end, both of these examples seem to work. What system are you running?
