### ISSUE TITLE
string with triple quote """ error

### ISSUE THREAD

**Issue by msongz** [runegan/jsxbin#24]
hi 
if string with triple quote like : `var x = """string"""`
after jsxbin this file
will cause problem
any idea ?

**Comment by runegan** [comment]
Does that work when it is not jsxbin? I don't think it is valid js.

**Comment by msongz** [comment]
@runegan when in jsx, it works fine

**Comment by runegan** [comment]
Could you test this with this? https://marketplace.visualstudio.com/items?itemName=Adobe.extendscript-debug
that is the official way to create jsxbin from adobe.

**Comment by msongz** [comment]
@runegan my fault, just find the triple quote """ string with new line could not be transcode to jsxbin with .toString() or .toSource()
